# Supabase Connection Configuration
[connections.supabase]
url = "https://wdvbesswsmrgjunpnxqu.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkdmJlc3N3c21yZ2p1bnBueHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTE2OTUsImV4cCI6MjA2MzI2NzY5NX0.ya-Kv5F-oHHaj1AG6UuwaKYGzV-eFEQ5iCBCfCwBwgQ"

# Supabase configuration for your toxicology_data database
# URL: https://wdvbesswsmrgjunpnxqu.supabase.co
# Anon key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkdmJlc3N3c21yZ2p1bnBueHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTE2OTUsImV4cCI6MjA2MzI2NzY5NX0.ya-Kv5F-oHHaj1AG6UuwaKYGzV-eFEQ5iCBCfCwBwgQ
